
DROP TABLE IF EXISTS CATEGORY;

CREATE TABLE CATEGORY (
  ID INT PRIMARY KEY,
  NAME VARCHAR(250) NOT NULL
);

INSERT INTO CATEGORY (ID, NAME) VALUES (1, 'Electronics');
INSERT INTO CATEGORY (ID, NAME) VALUES (2, 'Home Appliances');
INSERT INTO CATEGORY (ID, NAME) VALUES (3, 'Furniture');
  
DROP TABLE IF EXISTS PRODUCT;

CREATE TABLE PRODUCT (
  ID INT PRIMARY KEY,
  NAME VARCHAR(250) NOT NULL,
  PRICE DOUBLE DEFAULT NULL,
  CATEGORY_ID INT NOT NULL,
  FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORY(ID)
);

INSERT INTO PRODUCT (ID, NAME, PRICE, CATEGORY_ID) VALUES (1, 'LG 32 inch TV', 20000.00, 1);
INSERT INTO PRODUCT (ID, NAME, PRICE, CATEGORY_ID) VALUES (2, 'Sony 55 inch TV', 65000.00, 1);
INSERT INTO PRODUCT (ID, NAME, PRICE, CATEGORY_ID) VALUES (3, 'Samsung AC', 40000.00, 2);
INSERT INTO PRODUCT (ID, NAME, PRICE, CATEGORY_ID) VALUES (4, 'Panasonic Fridge', 30000.00, 2);
INSERT INTO PRODUCT (ID, NAME, PRICE, CATEGORY_ID) VALUES (5, 'Kent WaterPurifier', 15000.00, 2);
INSERT INTO PRODUCT (ID, NAME, PRICE, CATEGORY_ID) VALUES (6, 'Dining Table', 15000.00, 3);
  